"""initial migration

Revision ID: 04ec8ee4f0c1
Revises: 
Create Date: 2023-05-04 14:44:13.147907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ec8ee4f0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('imageURL', sa.String(length=300), nullable=True),
    sa.Column('videoURL', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('prepTime', sa.String(length=50), nullable=True),
    sa.Column('cookTime', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.String(length=50), nullable=True),
    sa.Column('ratingAvg', sa.String(length=10), nullable=True),
    sa.Column('ratingCount', sa.String(length=10), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_Admin', sa.Boolean(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.String(length=100), nullable=True),
    sa.Column('carbohydrate', sa.String(length=100), nullable=True),
    sa.Column('cholesterol', sa.String(length=100), nullable=True),
    sa.Column('fiber', sa.String(length=100), nullable=True),
    sa.Column('protein', sa.String(length=100), nullable=True),
    sa.Column('saturatedFat', sa.String(length=100), nullable=True),
    sa.Column('sodium', sa.String(length=100), nullable=True),
    sa.Column('sugar', sa.String(length=100), nullable=True),
    sa.Column('fat', sa.String(length=100), nullable=True),
    sa.Column('unsaturatedFat', sa.String(length=100), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.String(length=2), nullable=True),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savedUserRecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoppingList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingList')
    op.drop_table('savedUserRecipes')
    op.drop_table('Reviews')
    op.drop_table('Nutrition')
    op.drop_table('Ingredients')
    op.drop_table('Users')
    op.drop_table('Recipes')
    # ### end Alembic commands ###
